CREATE TABLE IF NOT EXISTS todo.users
(
    id          int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name        text not null,
    description text NOT NULL default '',
    email       text NOT NULL,
    password    text NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY (id)
);
