CREATE SCHEMA IF NOT EXISTS todo;

CREATE TABLE IF NOT EXISTS todo.items
(
    id          int8         NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created     timestamp    NOT NULL,
    description text NOT NULL default '',
    done        bool         NOT NULL default false,
    CONSTRAINT items_pkey PRIMARY KEY (id)
);
